//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendService.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> HundredsPlace { get; set; }
        public Nullable<int> TensPlace { get; set; }
        public Nullable<int> UnitPlace { get; set; }
        public Nullable<System.DateTime> DrawDate { get; set; }
    }
}
